### ISSUE TITLE
no subscribe api

### ISSUE THREAD

**Issue by howhuai** [AnthonySnow887/QtRedisClient#3]
i read the header file,i found there is no subscribe function to use,but has publish way.

**Comment by AnthonySnow887** [comment]
> i read the header file,i found there is no subscribe function to use,but has publish way.

All right. In this version of the library, I haven't added this method yet. I will try to do it soon. Thank you for pointing this out.

**Comment by howhuai** [comment]
> > i read the header file,i found there is no subscribe function to use,but has publish way.
> 
> All right. In this version of the library, I haven't added this method yet. I will try to do it soon. Thank you for pointing this out.

ohh，thanks for u quick reply and the QtRedisClient is really useful！！

**Comment by AnthonySnow887** [comment]
Redis Pub/Sub API mechanism added in revision 1.2.0
